;WITH RankedDischargeNote AS
(
    SELECT
        h.PAT_ENC_CSN_ID,
        h.NOTE_ID,
        h.IP_NOTE_TYPE_C,
        h.CREATE_INSTANT_DTTM,
        h.DATE_OF_SERVICE_DTTM,

        ROW_NUMBER() OVER
        (
            PARTITION BY h.PAT_ENC_CSN_ID
            ORDER BY
                COALESCE(
                    h.DATE_OF_SERVICE_DTTM,
                    h.CREATE_INSTANT_DTTM
                ) DESC,
                h.NOTE_ID DESC
        ) AS RN
    FROM dbo.HNO_INFO h
    WHERE h.IP_NOTE_TYPE_C = 5
),
DischargeNote AS
(
    SELECT
        r.PAT_ENC_CSN_ID,
        r.NOTE_ID,
        r.IP_NOTE_TYPE_C,
        r.CREATE_INSTANT_DTTM,
        r.DATE_OF_SERVICE_DTTM,

        STRING_AGG(
            CAST(t.NOTE_TEXT AS VARCHAR(MAX)),
            CHAR(13) + CHAR(10)
        ) WITHIN GROUP
        (
            ORDER BY t.LINE
        ) AS DISCHARGE_NOTE_TEXT

    FROM RankedDischargeNote r

    INNER JOIN dbo.HNO_NOTE_TEXT t
        ON r.NOTE_ID = t.NOTE_ID

    WHERE r.RN = 1

    GROUP BY
        r.PAT_ENC_CSN_ID,
        r.NOTE_ID,
        r.IP_NOTE_TYPE_C,
        r.CREATE_INSTANT_DTTM,
        r.DATE_OF_SERVICE_DTTM
),
MedicationSource AS
(
    SELECT DISTINCT
        ORDER_MED_ID,
        ORDER_SOURCE_C
    FROM dbo.ORDER_MEDINFO
    WHERE ORDER_SOURCE_C IN (41, 42, 54, 3)
)
SELECT
    peh.PAT_ID,
    peh.PAT_ENC_CSN_ID,
    p.PAT_MRN_ID,

    peh.DISCH_DISP_C,
    dd.NAME AS DISCH_DISP_NAME,
    peh.HOSP_DISCH_TIME,

    dn.NOTE_ID,
    dn.IP_NOTE_TYPE_C,
    c.NAME AS NOTE_TYPE_NAME,
    dn.CREATE_INSTANT_DTTM,
    dn.DATE_OF_SERVICE_DTTM,
    dn.DISCHARGE_NOTE_TEXT,

    om.ORDER_MED_ID,
    om.ORDERING_DATE,
    om.DESCRIPTION AS MEDICAL_DESCRIPTION,
    om.DOSAGE,
    om.QUANTITY,
    om.REFILLS,
    om.START_DATE,
    om.END_DATE,
    om.MDL_ID,
    om.AMB_MED_DISP_NAME,
    om.DISP_AS_WRITTEN_YN,
    om.ORDER_STATUS_C,

    ms.ORDER_SOURCE_C,
    s.NAME AS ORDER_SOURCE_NAME

FROM dbo.PAT_ENC_HSP peh

INNER JOIN DischargeNote dn
    ON peh.PAT_ENC_CSN_ID = dn.PAT_ENC_CSN_ID

INNER JOIN dbo.ORDER_MED om
    ON peh.PAT_ENC_CSN_ID = om.PAT_ENC_CSN_ID

INNER JOIN MedicationSource ms
    ON om.ORDER_MED_ID = ms.ORDER_MED_ID

LEFT JOIN dbo.ZC_ORDER_SOURCE s
    ON ms.ORDER_SOURCE_C = s.ORDER_SOURCE_C

LEFT JOIN dbo.ZC_NOTE_TYPE_IP c
    ON dn.IP_NOTE_TYPE_C = c.TYPE_IP_C

LEFT JOIN dbo.ZC_DISCH_DISP dd
    ON peh.DISCH_DISP_C = dd.DISCH_DISP_C

LEFT JOIN dbo.PATIENT p
    ON peh.PAT_ID = p.PAT_ID

WHERE peh.PAT_ID = '21485914'

-- Use this while validating one hospitalization:
-- AND peh.PAT_ENC_CSN_ID = 179617816

ORDER BY
    peh.HOSP_DISCH_TIME DESC,
    om.ORDERING_DATE DESC,
    om.ORDER_MED_ID;



DECLARE @PAT_ID VARCHAR(18) = '00925869';

SELECT DISTINCT
    adt.PAT_ID,
    adt.PAT_ENC_CSN_ID,
    adt.EVENT_ID,
    adt.EFFECTIVE_TIME AS ADMISSION_TIME,
    adt.EVENT_TYPE_C,
    et.NAME AS EVENT_TYPE_NAME,
    adt.EVENT_SUBTYPE_C,
    est.NAME AS EVENT_SUBTYPE_NAME,
    adt.PAT_CLASS_C,
    pc.NAME AS PATIENT_CLASS_NAME,
    adt.DEPARTMENT_ID
FROM dbo.CLARITY_ADT adt
LEFT JOIN dbo.ZC_EVENT_TYPE et
    ON adt.EVENT_TYPE_C = et.EVENT_TYPE_C
LEFT JOIN dbo.ZC_EVENT_SUBTYPE est
    ON adt.EVENT_SUBTYPE_C = est.EVENT_SUBTYPE_C
LEFT JOIN dbo.ZC_PAT_CLASS pc
    ON adt.PAT_CLASS_C = pc.ADT_PAT_CLASS_C
WHERE adt.PAT_ID = @PAT_ID
  AND adt.EVENT_TYPE_C = 1
  AND adt.EFFECTIVE_TIME >= DATEFROMPARTS(YEAR(GETDATE()), 1, 1)
  AND adt.EFFECTIVE_TIME <  DATEFROMPARTS(YEAR(GETDATE()) + 1, 1, 1)
  AND adt.DELETE_TIME IS NULL
  AND ISNULL(est.NAME, '') <> 'Canceled'
ORDER BY adt.EFFECTIVE_TIME;




SELECT DISTINCT
    adt.PAT_ID,
    adt.PAT_ENC_CSN_ID,
    adt.EFFECTIVE_TIME AS ADMISSION_TIME,
    adt.EVENT_TYPE_C,
    adt.EVENT_SUBTYPE_C,
    adt.PAT_CLASS_C,
    adt.BASE_PAT_CLASS_C,
    adt.FIRST_IP_IN_IP_YN
FROM dbo.CLARITY_ADT adt
WHERE adt.PAT_ID = '21485914'
  AND adt.EVENT_TYPE_C = 1
  AND adt.EFFECTIVE_TIME >= DATEFROMPARTS(YEAR(GETDATE()), 1, 1)
  AND adt.EFFECTIVE_TIME <  DATEFROMPARTS(YEAR(GETDATE()) + 1, 1, 1)
  AND adt.DELETE_TIME IS NULL
ORDER BY adt.EFFECTIVE_TIME;


SELECT
    adt.PAT_ID,
    COUNT(DISTINCT adt.PAT_ENC_CSN_ID) AS INPATIENT_ADMISSION_COUNT
FROM dbo.CLARITY_ADT adt
WHERE adt.PAT_ID = '21485914'
  AND adt.EFFECTIVE_TIME >= DATEFROMPARTS(YEAR(GETDATE()), 1, 1)
  AND adt.EFFECTIVE_TIME <  DATEFROMPARTS(YEAR(GETDATE()) + 1, 1, 1)
  AND adt.FIRST_IP_IN_IP_YN = 'Y'
  AND adt.DELETE_TIME IS NULL
GROUP BY adt.PAT_ID;


SELECT DISTINCT
    adt.PAT_ID,
    adt.PAT_ENC_CSN_ID,
    adt.EFFECTIVE_TIME AS INPATIENT_ADMISSION_TIME,
    adt.EVENT_TYPE_C,
    adt.EVENT_SUBTYPE_C,
    adt.PAT_CLASS_C
FROM dbo.CLARITY_ADT adt
WHERE adt.PAT_ID = '21485914'
  AND adt.EFFECTIVE_TIME >= DATEFROMPARTS(YEAR(GETDATE()), 1, 1)
  AND adt.EFFECTIVE_TIME <  DATEFROMPARTS(YEAR(GETDATE()) + 1, 1, 1)
  AND adt.FIRST_IP_IN_IP_YN = 'Y'
  AND adt.DELETE_TIME IS NULL
ORDER BY adt.EFFECTIVE_TIME;



SELECT
    peh.PAT_ID,
    peh.PAT_ENC_CSN_ID,
    peh.HSP_ACCOUNT_ID,

    peh.HOSP_ADMSN_TIME,
    peh.HOSP_DISCH_TIME,

    peh.DISCH_DISP_C,
    disp.NAME AS DISCHARGE_DISPOSITION,

    peh.DISCH_DEST_C,

    dx.LINE AS DIAGNOSIS_SEQUENCE,
    CASE
        WHEN dx.LINE = 1 THEN 'Principal Final Diagnosis'
        ELSE 'Secondary Final Diagnosis'
    END AS DIAGNOSIS_TYPE,

    dx.DX_ID,
    edg.DX_NAME,
    edg.REF_BILL_CODE AS ICD_CODE,
    edg.REF_BILL_CODE_SET_C AS ICD_CODE_SET

FROM PAT_ENC_HSP peh

INNER JOIN HSP_ACCT_DX_LIST dx
    ON peh.HSP_ACCOUNT_ID = dx.HSP_ACCOUNT_ID

INNER JOIN CLARITY_EDG edg
    ON dx.DX_ID = edg.DX_ID

LEFT JOIN ZC_DISCH_DISP disp
    ON peh.DISCH_DISP_C = disp.DISCH_DISP_C

WHERE peh.HOSP_DISCH_TIME IS NOT NULL

-- Use the principal final diagnosis only
AND dx.LINE = 1

-- Replace with the post-acute disposition codes used by your organization
AND peh.DISCH_DISP_C IN
(
    /* SNF code,
       inpatient rehabilitation code,
       LTACH code,
       home-health code,
       hospice code */
);


SELECT
    h.PAT_ENC_CSN_ID,
    h.NOTE_ID,
    h.NOTE_DESC,
    h.IP_NOTE_TYPE_C,
    nei.NOTE_STATUS_C,
    nei.NOTE_FILE_TIME_DTTM,
    nei.AUTH_LNKED_PROV_ID
FROM HNO_INFO h
INNER JOIN NOTE_ENC_INFO nei
    ON h.NOTE_ID = nei.NOTE_ID
WHERE h.PAT_ENC_CSN_ID = @PAT_ENC_CSN_ID
  AND h.IP_NOTE_TYPE_C = @DISCHARGE_SUMMARY_NOTE_TYPE
  AND nei.NOTE_STATUS_C IN (
      @SIGNED_STATUS,
      @FINALIZED_STATUS,
      @COSIGNED_STATUS
  )
ORDER BY nei.NOTE_FILE_TIME_DTTM DESC;
