SELECT DISTINCT
    adt.PAT_ID,
    adt.PAT_ENC_CSN_ID,
    adt.EFFECTIVE_TIME AS ADMISSION_TIME,
    adt.EVENT_TYPE_C,
    adt.EVENT_SUBTYPE_C,
    adt.PAT_CLASS_C,
    adt.BASE_PAT_CLASS_C,
    adt.FIRST_IP_IN_IP_YN
FROM dbo.CLARITY_ADT adt
WHERE adt.PAT_ID = '21485914'
  AND adt.EVENT_TYPE_C = 1
  AND adt.EFFECTIVE_TIME >= DATEFROMPARTS(YEAR(GETDATE()), 1, 1)
  AND adt.EFFECTIVE_TIME <  DATEFROMPARTS(YEAR(GETDATE()) + 1, 1, 1)
  AND adt.DELETE_TIME IS NULL
ORDER BY adt.EFFECTIVE_TIME;


SELECT
    adt.PAT_ID,
    COUNT(DISTINCT adt.PAT_ENC_CSN_ID) AS INPATIENT_ADMISSION_COUNT
FROM dbo.CLARITY_ADT adt
WHERE adt.PAT_ID = '21485914'
  AND adt.EFFECTIVE_TIME >= DATEFROMPARTS(YEAR(GETDATE()), 1, 1)
  AND adt.EFFECTIVE_TIME <  DATEFROMPARTS(YEAR(GETDATE()) + 1, 1, 1)
  AND adt.FIRST_IP_IN_IP_YN = 'Y'
  AND adt.DELETE_TIME IS NULL
GROUP BY adt.PAT_ID;


SELECT DISTINCT
    adt.PAT_ID,
    adt.PAT_ENC_CSN_ID,
    adt.EFFECTIVE_TIME AS INPATIENT_ADMISSION_TIME,
    adt.EVENT_TYPE_C,
    adt.EVENT_SUBTYPE_C,
    adt.PAT_CLASS_C
FROM dbo.CLARITY_ADT adt
WHERE adt.PAT_ID = '21485914'
  AND adt.EFFECTIVE_TIME >= DATEFROMPARTS(YEAR(GETDATE()), 1, 1)
  AND adt.EFFECTIVE_TIME <  DATEFROMPARTS(YEAR(GETDATE()) + 1, 1, 1)
  AND adt.FIRST_IP_IN_IP_YN = 'Y'
  AND adt.DELETE_TIME IS NULL
ORDER BY adt.EFFECTIVE_TIME;



SELECT
    peh.PAT_ID,
    peh.PAT_ENC_CSN_ID,
    peh.HSP_ACCOUNT_ID,

    peh.HOSP_ADMSN_TIME,
    peh.HOSP_DISCH_TIME,

    peh.DISCH_DISP_C,
    disp.NAME AS DISCHARGE_DISPOSITION,

    peh.DISCH_DEST_C,

    dx.LINE AS DIAGNOSIS_SEQUENCE,
    CASE
        WHEN dx.LINE = 1 THEN 'Principal Final Diagnosis'
        ELSE 'Secondary Final Diagnosis'
    END AS DIAGNOSIS_TYPE,

    dx.DX_ID,
    edg.DX_NAME,
    edg.REF_BILL_CODE AS ICD_CODE,
    edg.REF_BILL_CODE_SET_C AS ICD_CODE_SET

FROM PAT_ENC_HSP peh

INNER JOIN HSP_ACCT_DX_LIST dx
    ON peh.HSP_ACCOUNT_ID = dx.HSP_ACCOUNT_ID

INNER JOIN CLARITY_EDG edg
    ON dx.DX_ID = edg.DX_ID

LEFT JOIN ZC_DISCH_DISP disp
    ON peh.DISCH_DISP_C = disp.DISCH_DISP_C

WHERE peh.HOSP_DISCH_TIME IS NOT NULL

-- Use the principal final diagnosis only
AND dx.LINE = 1

-- Replace with the post-acute disposition codes used by your organization
AND peh.DISCH_DISP_C IN
(
    /* SNF code,
       inpatient rehabilitation code,
       LTACH code,
       home-health code,
       hospice code */
);


SELECT
    h.PAT_ENC_CSN_ID,
    h.NOTE_ID,
    h.NOTE_DESC,
    h.IP_NOTE_TYPE_C,
    nei.NOTE_STATUS_C,
    nei.NOTE_FILE_TIME_DTTM,
    nei.AUTH_LNKED_PROV_ID
FROM HNO_INFO h
INNER JOIN NOTE_ENC_INFO nei
    ON h.NOTE_ID = nei.NOTE_ID
WHERE h.PAT_ENC_CSN_ID = @PAT_ENC_CSN_ID
  AND h.IP_NOTE_TYPE_C = @DISCHARGE_SUMMARY_NOTE_TYPE
  AND nei.NOTE_STATUS_C IN (
      @SIGNED_STATUS,
      @FINALIZED_STATUS,
      @COSIGNED_STATUS
  )
ORDER BY nei.NOTE_FILE_TIME_DTTM DESC;
